name: Middleman Build and Sync

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build and sync
        run: docker run -v $PWD:/app markupboy/markupboy:latest make build
      - uses: actions/upload-artifact@v2
        with:
          name: markupboy-site-build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: markupboy-site-build
      - uses: lbertenasco/s3-deploy@v1
        with:
          folder: "/home/runner/work/markupboy/markupboy"
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          dist-id: ${{ secrets.AWS_CLOUNDFRONT_DIST_ID }}
          invalidation: "/*"
