name: Build and Deploy Astro to S3

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          npm install
          npm run build
      - name: store artifact
        uses: actions/upload-artifact@v2
        with:
          name: markupboy-site-build
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: markupboy-site-build
      - uses: lbertenasco/s3-deploy@v1
        with:
          folder: "/home/runner/work/markupboy/markupboy"
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          dist-id: ${{ secrets.AWS_CLOUNDFRONT_DIST_ID }}
          invalidation: "/*"
